  
version: '3'
services:
  web:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    # command:  bash -c "make start_backend && make start front_end"
    container_name: nuxt-apollo
    ports:
      - "80:3000"
    depends_on:
      - prisma

  prisma:
    container_name: api-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/var/lib/mongo
  

 